### PR TITLE
Implement Kirby\Exception in Kirby\Cms

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by distantnative** [comment]
@bastianallgeier @lukasbestle I tried to rebase this branch as described by Lukas. However, now it still doesn't seem clean, but with a lot of the session changes interwoven. Ideas?

**Comment by lukasbestle** [comment]
@distantnative I have rebased again. The reason why the session stuff is displayed was that the PR was sent against the `master` branch, which doesn't yet contain the changes. Changing to `develop` fixed it.

**Comment by distantnative** [comment]
@lukasbestle doh, that happened too often lately :( thank you!

**Comment by distantnative** [comment]
@bastianallgeier @lukasbestle Could you have a look if I am on the right track with this? E.g. do we need to translate these actually or would normal exceptions or our exceptions with `translate => false` sufficient?

```
   "error.page.textfile.move": "The page textfile for \"{slug}\" could not be moved",
    "error.page.directory.create": "The page directory for \"{slug}\" cannot be created",
    "error.page.directory.move": "The page directory for \"{slug}\" cannot be moved",
    "error.file.props.missing": "Please provide the \"source\" and \"parent\" props for the File",
    "error.collection.object.invalid": "Invalid object in collection. Accepted: \"{accept}\"",
    "error.collection.notFound": "The collection \"{name}\" cannot be found",
```

**Comment by lukasbestle** [comment]
I think that all of those are errors of the category "internal error that actually shouldn't occur at all".

In my opinion we don't need to translate those, but we also shouldn't expose the English error to the Panel UI directly.
Maybe we should somehow mark those "internal" exceptions somehow so that the Panel can instead display a generic "An internal error occured" message that is translated to the current user locale. However we need to make sure that the actual error is always available with all details (maybe behind a "more information" accordion) so that developers can find the issue. I think that's a good compromise.

**Comment by distantnative** [comment]
I added `Exception::isTranslated()`.

**Pull request merged**
