### PR TITLE
TimeField: rename hours prop to military 

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by distantnative** [comment]
Yes, that's what it means. Honestly, I'd be happy if we find a better name. But `hours: 24` somehow also didn't feel so right (and I kind also wanted to use `this.hours` for something else in the Vue Component 😆)

**Comment by lukasbestle** [comment]
I think the term "military time" is confusing for users who haven't heard that term in this context before.

There are also other formats like the Thai six-hour clock. We don't have to support that one, but I think that an option that can just be true or false doesn't really reflect that there may be more formats. If we want to rename the option, what about `format: 24/12`?

**Comment by distantnative** [comment]
`format` sounds good and intuitive to me.

**Comment by distantnative** [comment]
@bastianallgeier would `format` work for you?

**Comment by distantnative** [comment]
Changed to format, ready for merge @bastianallgeier

**Comment by distantnative** [comment]
@lukasbestle @bastianallgeier just realized that we already have a `DateField::format()`Let's stick with `hours: 12/24`.

**Comment by lukasbestle** [comment]
What about `notation` then? I think this is actually the most correct term.

**Comment by bastianallgeier** [comment]
Ohhh, that's a good one!

**Comment by distantnative** [comment]
👍✅

**Pull request closed without merging**
