### PR TITLE
Data: Fix handling of corrupted data

### PR DESCRIPTION
**Pull request by lukasbestle**
If a file can’t be read as the contents are corrupted, we can’t return an array. I have opted to return null in this case.

**There is one issue**: Nullable return types (the question mark in front of the return type) were introduced in PHP 7.1. If we need support for PHP 7.0, we need to remove that return type declaration entirely.

### CODE REVIEW

**Comment by lukasbestle** [comment]
I think so too. PHP 7.0 is a no-brainer as it really adds a lot of benefit compared to PHP 5, but 7.1 might not be worth it for the small benefits.

We can (and should in my opinion!) upgrade to 7.1 support as soon as PHP 7.0 is end-of-life this December.

**Comment by bastianallgeier** [comment]
Let's stick with PHP 7.0 for the first release and upgrade later!

**Comment by lukasbestle** [comment]
Alright, done! BTW: Why is PHP 7.0 not part of the test chain in the Travis configuration?

**Comment by distantnative** [comment]
Just wondering if returning `null` on corrupted data is ideal or if any kind of error should be rather thrown?

**Comment by lukasbestle** [comment]
Good point. I'm not sure about this either.

**Comment by lukasbestle** [comment]
@bastianallgeier @distantnative Now ready for review again. :)

**Pull request merged**
