### PR TITLE
Add seconds prop to Time mixin, default step = 5

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by distantnative** [comment]
I did it cause you have them in the TimeField format in the backend. And since I think it should be optional, we would need a `seconds` option for the blueprints.

**Comment by bastianallgeier** [comment]
Ahh, I see. The big question is if we really want them in the time field at all :) Seems like a typical feature that adds complexity and is used in 0.0009% of all installations.

**Comment by distantnative** [comment]
I'd rather not have them. Just realized a new issue with them. But then we should remove them from the format als well.

**Comment by bastianallgeier** [comment]
Yep, sounds way better for me!

**Pull request closed without merging**
