### PR TITLE
Cookie class refactoring

### PR DESCRIPTION
**Pull request by lukasbestle**
As discussed earlier, I have refactored the Cookie class as part of the new Session package I'm building.

There is **one part I'm not sure about**: In the CMS, we are switching more and more from long argument lists to option arrays. I think that this would make a lot of sense in the Cookie class as well, so setting a cookie would look like this:

```php
// old
Cookie::set('mycookie', 'hello', 60, '/', 'getkirby.com', true, true);

// new
Cookie::set('mycookie', 'hello', [
  'lifetime' => 60,
  'path' => '/',
  'domain' => 'getkirby.com',
  'secure' => true,
  'httpOnly' => true
]);
```

What do you think? Should we rather preserve backwards-compatibility here or move forward with an easier to read and more flexible syntax using an option array? Or a totally different solution?

### CODE REVIEW

**Comment by bastianallgeier** [comment]
@lukasbestle I like the array options a lot. Especially in this case. Makes the code so much easier to read!

**Comment by bastianallgeier** [comment]
@lukasbestle do you want to put into this PR or create a new one for it?

**Comment by lukasbestle** [comment]
@bastianallgeier I have added this to this PR as an additional commit. I have also introduced a feature that makes it possible to use absolute expiry times for the cookie.

**Comment by lukasbestle** [comment]
@bastianallgeier @distantnative After improving some more stuff, this PR is now ready for review again. :)

**Pull request merged**
